services:
  db:
    image: mysql
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    volumes:
      - ./db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: "./"
    container_name: app
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./src/view:/app/src/view
volumes:
  db-data: